# Generated by Django 3.0.4 on 2020-07-13 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import langiAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('langiAPI', '0002_auto_20200629_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_front', models.CharField(max_length=5)),
                ('language_back', models.CharField(max_length=5)),
                ('text_front', models.TextField(blank=True)),
                ('text_back', models.TextField(blank=True)),
                ('example_sentence_one', models.TextField(blank=True)),
                ('example_sentence_two', models.TextField(blank=True)),
                ('example_sentence_three', models.TextField(blank=True)),
                ('image_front', models.TextField(blank=True)),
                ('image_back', models.TextField(blank=True)),
                ('main_image', models.FileField(blank=True, null=True, upload_to=langiAPI.models.upload_img_path)),
                ('sound', models.FileField(blank=True, null=True, upload_to=langiAPI.models.upload_sound_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('repeat_date', models.DateField(default=datetime.date.today)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langiAPI.Deck')),
            ],
        ),
    ]
