# Generated by Django 3.0.4 on 2020-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langiAPI', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='language_back',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='language_front',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
