# Generated by Django 3.0.4 on 2020-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langiAPI', '0004_auto_20200720_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='allAnswers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='card',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='sumAnswers',
            field=models.FloatField(default=0.0),
        ),
    ]
