# Generated by Django 3.0.4 on 2020-08-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langiAPI', '0005_auto_20200731_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snake_score', models.IntegerField(default=0)),
                ('drag_drop_score', models.IntegerField(default=0)),
                ('again', models.IntegerField(default=0)),
                ('very_hard', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('easy', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langiAPI.Deck')),
            ],
        ),
    ]
