# Generated by Django 3.0.4 on 2020-08-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langiAPI', '0006_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.AlterField(
            model_name='activity',
            name='deck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='langiAPI.Deck'),
        ),
    ]
